// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx9jZBcY2F7dicg_Hqn6OwI7Txk2qzu54',
    appId: '1:557164602289:web:8b1e99ff4bdfe58c2e9390',
    messagingSenderId: '557164602289',
    projectId: 'workbridge-1b2e2',
    authDomain: 'workbridge-1b2e2.firebaseapp.com',
    storageBucket: 'workbridge-1b2e2.firebasestorage.app',
    measurementId: 'G-2T50HPY8P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfovjXGQoB1Cwi7PaVYi7dppan5aAmDIg',
    appId: '1:557164602289:android:fb511cffe966cd0a2e9390',
    messagingSenderId: '557164602289',
    projectId: 'workbridge-1b2e2',
    storageBucket: 'workbridge-1b2e2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7IfDCFpSRbNXzgXpZp-mUQo2R6BKQOzo',
    appId: '1:557164602289:ios:515f6153da29e1b32e9390',
    messagingSenderId: '557164602289',
    projectId: 'workbridge-1b2e2',
    storageBucket: 'workbridge-1b2e2.firebasestorage.app',
    iosBundleId: 'com.example.workbridge',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7IfDCFpSRbNXzgXpZp-mUQo2R6BKQOzo',
    appId: '1:557164602289:ios:515f6153da29e1b32e9390',
    messagingSenderId: '557164602289',
    projectId: 'workbridge-1b2e2',
    storageBucket: 'workbridge-1b2e2.firebasestorage.app',
    iosBundleId: 'com.example.workbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx9jZBcY2F7dicg_Hqn6OwI7Txk2qzu54',
    appId: '1:557164602289:web:e762269e747828ef2e9390',
    messagingSenderId: '557164602289',
    projectId: 'workbridge-1b2e2',
    authDomain: 'workbridge-1b2e2.firebaseapp.com',
    storageBucket: 'workbridge-1b2e2.firebasestorage.app',
    measurementId: 'G-VV1FFSEFMZ',
  );
}
